### ISSUE TITLE
Ender tether crashing when trying to interrupt teleport

### ISSUE THREAD

**Issue by ceiphas** [Darkhax-Minecraft/Dark-Utilities#102]
https://paste.ee/p/qu7Ti

i placed an ender tether in my mob farm to prevent endermen to port out of it.

As soon as an enderman spawns and tries to escape, the game crashes with this error.

it looks like the issue #78 but i use the "fixed" version of dark-utilities 1.2.0.147

**Comment by darkhax** [comment]
This issue keeps popping up, and goes through several months of being fixed until some mod changes something in a weird way. I will backport some of the recent 1.12 fixes to 1.11 and see if that helps.

**Comment by maruohon** [comment]
It seems that you are using the `getCollisionBoundingBox()` method in the 1.10.2 and 1.11.2 versions, which in vanilla is null for everything except boats, minecarts and shulkers. In the master branch however, you are already using the `getEntityBoundingBox()` method, which is correct in this case.

I'm also not sure how the Tether's area has worked if you initialize it when the TileEntity is created, as the actual position of the TE is only set when `readFromNBT()` is called for it. This also seems to have been fixed in master already.

**Comment by darkhax** [comment]
Yep, these were both issues fixed in 1.12. I am going to be backporting them, as mentioned above.
