### ISSUE TITLE
[1.12] Tessalating Block (sneaky) causes SMP Crash

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Dark-Utilities#108]
Crash log @ https://puu.sh/wMHEr/4d973f2907.txt

**Comment by darkhax** [comment]
Just to recap what we discussed in a DM. It seems this is a corrupted sneaky block. It's not possible for me to catch the error, and due to Forge making their fluid model private, reflection is required to catch and prevent this issue in the future. I will work on something, but it's outside the scope of this issue.
