### ISSUE TITLE
Ender Tether pulling/disconnecting players using Ender Book's from Cyclic

### ISSUE THREAD

**Issue by Jomeaga** [Darkhax-Minecraft/Dark-Utilities#155]
Pack: Enigmatica 2 Expert version 1.36
Using:
Dark Utils-1.12-1.8.211
Cyclic-1.12-1.17.0
Forge-14.23.4.2751

When players use an Ender Book within range of an Ender Tether, they either get pulled to the tether or disconnect from the server.

**Comment by darkhax** [comment]
The ender tether disrupting ender books is specifically intended. The ender tether will redirect all ender teleportation including ender pearls, the ender book, resonant ender fluid, and many other things. Being disconnected from the server is not intentional though, and more info would be needed. Such as the disconnected message, the server log, and the client log of the person who disconnected.
