### ISSUE TITLE
Fake TNT causes damage to entities in DarkUtils-1.12.2-1.8.219

### ISSUE THREAD

**Issue by Vintschente** [Darkhax-Minecraft/Dark-Utilities#171]
Version: DarkUtils-1.12.2-1.8.219

Issue: Fake TNT causes damage to other entities like normal TNT but doesn't cause damage to nearby blocks.

That was a nice "prank" I pulled on one of my friends and his animal farm...

**Comment by Sewef** [comment]
I took a quick look on minecraft code.
entity damages are handled in `doExplosionA`, to prevent this we need an Override in `ExplosionFakeTnt` class. I think it's the simpliest way to fix this issue ^_^

**Comment by darkhax** [comment]
Thank you for the issue report, and sorry for any issues this caused. If you would like, I can include an apology to your friend in the changelog when this issue is fixed. 

@Sewef I am going to implement the override in the Bookshelf explosion class so I can add a new method to handle damage instead of overriding the entire doExplosionA method.
