### ISSUE TITLE
Thaumcraft Pechs and Player Traps

### ISSUE THREAD

**Issue by shadeaux83** [Darkhax-Minecraft/Dark-Utilities#172]
A server I am on just crashed and based on the crash report it sounds like Dark Utilities Player Traps don't like Thaumcraft Pech mobs, or the other way around.  Just wanted to mention it in case that is, in fact, an issue.

**Comment by VallenFrostweaver** [comment]
Sure thing. Thank you. 
https://pastebin.com/U0HCNvQE

**Comment by darkhax** [comment]
Thanks for providing the crash info. This looks like an issue with Thaumcraft itself, and likely isn't related to any other mod. Specifically, it looks like the Pech AI is being accessed and updated in a way that is not thread safe. This is related to the Pech being update ticked, rather than the Pech being killed or damaged. An alternative possibility is another mod on the server is accessing the AI in a non thread safe way. 

I've set up a server with Thaumcraft and am going to let a pech farm with command blocks run for a few hours to see if I can get any additional information, or find a reliable way to reproduce the issue.

**Comment by VallenFrostweaver** [comment]
If it helps any it was in FTB Presents StoneBlock 2 modpack v1.1.1

**Comment by darkhax** [comment]
So I left a setup running for 18h35m on my server, it was spawning ~84 pechs a second and killing them on player plates. There were no crashes, so I think it's safe to rule out Dark Utils completely. This is either an issue with Thaumcraft itself, or some other mod that is accelerating mobs, like a watch of flowing time or acceleration wands that affects entities. Sorry I couldn't be more helpful in tracking it down.
