### ISSUE TITLE
[1.14] game crashes when placing down crucible

### ISSUE THREAD

**Issue by BardGitH** [Darkhax-Minecraft/Dark-Utilities#184]
My game crashes when placing down any of the crucibles added by Dark Utilities in 1.14

**Comment by WenXin20** [comment]
I got the same crash, but here is the [crash report](https://gist.github.com/WenXin20/99da1030fafa86eea70eb3c054cc9031).
I'm using `Forge v28.1.90`.

**Comment by BardGitH** [comment]
I didn't get a crash report so it might not be the same crash, either that or my instance was being weird

**Comment by Darkhax** [comment]
Thanks for the report, I can reproduce the issue on my end as well. This looks like an extremely weird edge case in Forge Gradle and the MCP remapper. Currently looking into it with other forge devs. If we don't find a solution in a timely manner I will put out a hotfix in DU2 to get around this issue.

**Comment by Darkhax** [comment]
The bug was traced back to a signature error when compiling mods with ForgeGradle. It may take them some time to properly fix it. If you're curious about the issue you can read more here: https://github.com/MinecraftForge/ForgeGradle/issues/636 

In the mean time I have fixed this issue on my end by simply disabling the signing of my jars while they sort things out. The new release on CF should work fine.

**Comment by WenXin20** [comment]
I got a different crash this time when placing down the crucible with `Dark Utils v2.0.3`
[Crash Report](https://gist.github.com/WenXin20/cb1c85d78c06a2c3e132b133eac8778c)

**Comment by Darkhax** [comment]
You need to update Bookshelf to use with 2.0.3

**Comment by WenXin20** [comment]
Thanks, I'll try that.
