### ISSUE TITLE
Game crash upon mob collides with the player damage plate

### ISSUE THREAD

**Issue by S0ar1ngDeath** [Darkhax-Minecraft/Dark-Utilities#196]
when a test subject spider step on the plate I mentioned(that plate which I've been told that will do player damage to the mob that is currently stepping on it.), the game crashed while do whatever things to the spider that might interfere with saving or reading its data.
It should be clear that the spider is not in any vehicle, while your mod clearly didn't think about that and when reading this, you **tried to use a null pointer** which is never a good thing. And there goes my game.
[crash-2019-12-30_22.33.06-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4011862/crash-2019-12-30_22.33.06-server.txt)

**Comment by Darkhax** [comment]
Thanks for reporting this issue, however your understanding of the crash is completely incorrect. The actual issue is Ama's Damage Indicator which is trying to send a packet to a fake player. Fake players are part of Minecraft Forge's spec and specifically do not allow packets to be sent to them. 

https://github.com/JibayMcs/Ama-s-Damage-Indicator
