### ISSUE TITLE
[Feature Request] Enchantable player damage trap

### ISSUE THREAD

**Issue by kingquote** [Darkhax-Minecraft/Dark-Utilities#239]
It would be great if we were able to add enchantments like Fortune or Sharpness to the player damage trap.

**Comment by Darkhax** [comment]
Hello,

The player damage trap is not enchantable for a few reasons.

1. Other trap blocks already provide similar functionality to enchantments. I would rather give players the pieces to make their own farms rather than an all in one solution. For example some players combine plates with vector plates and make a trap loop pushing mobs over and over.
2. Enchantments would require the trap to be a Tile Entity. These have a small impact on performance but can add up if you have a lot of them. The current trap is the same as a normal block and has a performance impact similar to a block of stone. I like that these traps give players a highly performant option compared to methods added by other mods which can do more but perform worse as they scale.
