### ISSUE TITLE
No infusion recipe for Recall focus

### ISSUE THREAD

**Issue by Periphera** [Darkhax-Minecraft/Dark-Utilities#3]
v1.8.9-1.0.0.18

There is no infusion recipe showing for the Recall Focus in the Thauminomicon. It does have the description though. JEI doesn't show the recipe either, just a description entry.

**Comment by darkhax** [comment]
The recipes are not showing, because they have not been added yet. It's still a WIP feature. When it does get added, players who have completed the research will not have to do it again. The current thing left to add is a proper way to balance the focus (more vis the further away you are from the target) and a decent recipe.

**Comment by darkhax** [comment]
Thaumcraft support is temporarily removed for 1.9 and 1.8 is no longer supported.
