### ISSUE TITLE
[BUG] Redstone Randomizer not working?

### ISSUE THREAD

**Issue by BioMasterZap** [Darkhax-Minecraft/Dark-Utilities#303]
### Minecraft Version

1.20.4

### Mod Version

19.0.5

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

So this might be user error, but for the Fabric 1.20.4 version of the mod, I cannot get the Redstone Randomizer to output any signal. After noticing it didn't seem to be doing anything, I set up dozens of them facing pistons with wood blocks on a test world and set the tick speed to 10,000 per second and after several minutes, not a single one activated to push the block out. I also did power some of them in case that mattered. Another thing I noticed is that the Redstone Randomizer cannot be placed facing up or down, unlike Observers.

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue. It looks like Mojang slightly changed how blocks tick in 1.20.4 so the block would never flip state. This has been fixed and a new version is currently being processed by CurseForge. You can find the file [here (19.0.6)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/5165846) when it's done processing. 

> Another thing I noticed is that the Redstone Randomizer cannot be placed facing up or down, unlike Observers.

This was an intentional part of the design. I feel a lot of the fun in redstone is building big contraptions from smaller ones. It's tempting for mods to add new blocks that are perfect in all scenarios and reduce the size and complexity of these builds, but that can take the fun out of it and also make those features redundant. Only emitting a signal horizontally is my attempt to strike a balance between the two as it still leaves issues for players to solve and is consistent with other similar redstone components like repeaters.
