### ISSUE TITLE
All vector plates forced south [1.10.2]

### ISSUE THREAD

**Issue by Yamza** [Darkhax-Minecraft/Dark-Utilities#51]
As stated, all previously existing vector plates are forced facing south, and new ones can only be placed facing south and are not able to be rotated.

Ver, DarkUtilities-1.10.2-1.1.7.116
Playing on a server running the current version of All The Mods: Expert

**Comment by darkhax** [comment]
Whoops, sorry. The issue was fixed in 117, but the build server failed due to [this](https://github.com/MinecraftForge/ForgeGradle/issues/312) issue in ForgeGradle. I've since corrected the issue, and build 118 is [now on CurseForge](https://minecraft.curseforge.com/projects/dark-utilities/files/2391443).
