### ISSUE TITLE
Ender Hopper does not let items despawn

### ISSUE THREAD

**Issue by thebagmaster** [Darkhax-Minecraft/Dark-Utilities#54]
Not sure if this is intended, but if there is nowhere to put the items and items keep dropping they will accumulate and create particles until bad things happen with server and client tickrate.

**Comment by thebagmaster** [comment]
Also, the items were inside of a extra utilities iron spike if that is related.

**Comment by darkhax** [comment]
I can't reproduce this issue. The item will despawn at the regular despawn time.

**Comment by DrDelius** [comment]
I know I'm late, but couldn't this be a vanilla issue, in that as long as the same stack-able item keeps getting dropped the resulting entity stacks will not despawn until items stop being added, the issue being that a huge number of entities causes a massive load on your server, with the ender hopper itself causing it to be worse because of the extra particle rendering? I've seen the first bit hit a server a while back, but I'm assuming the vanilla mechanics on that still work the same. I wouldn't think that is something you even could fix on your side.
