### ISSUE TITLE
Draconic Evolution recipe conflict

### ISSUE THREAD

**Issue by PapiDimmi** [Darkhax-Minecraft/Dark-Utilities#63]
[Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution) changes the recipe of the End crystal and makes it ridiculously expensive, as it requires a Nether star.

![end crystal recipe draconic evolution annoyance](https://cloud.githubusercontent.com/assets/25916106/24831648/1a5f9552-1c9e-11e7-87dd-14d644c702a1.png)

This means that the portal charm from Dark Utilities, which requires an End crystal, is ridiculously expensive as well.

@darkhax I was wondering if you could please change the recipe of the portal charm so that it requires something else, like just an eye of ender—or something else that’s not super expensive like the end crystal is when Draconic Evolution is installed. If you don’t want to do that, you can just detect if Draconic Evolution is installed, and if it is, the recipe of the portal charm can be changed automagically.

**Comment by darkhax** [comment]
I strongly believe that mod authors should try and use the vanilla content respectfully, to mitigate the amount of conflicts. When Draconic Evolution tweaked this recipe, they broke the balancing for every mod which uses this item, as a way to bypass a vanilla mechanic. IMO, Draconic Evolution should have taken a less intrusive approach here. For example, they could have changed the behavior of the vanilla crystal so that it doesn't re-summon the dragon. 

I am also not a fan of making exceptions in my code for when another mod is loaded, unless I am specifically adding content based around that mod, or making API calls to that mod. Instead, I will probably just add the recipe you suggested as a second one.

**Comment by PapiDimmi** [comment]
I fully agree with you. Draconic Evolution should add a new block, not use an existing one and tweak its recipe.

I was really confused when I saw that the portal charm requires a Nether star.

**Comment by PapiDimmi** [comment]
Thanks for the fix, @darkhax! :heart:
