### ISSUE TITLE
Null Charm does not function while in the Baubles charm slot

### ISSUE THREAD

**Issue by Febilian** [Darkhax-Minecraft/Dark-Utilities#81]
It works while in the inventory, but not in the baubles slot. Kinda defeats the purpose of it being a bauble.

1.2.0.126 Dark Utilities
1.4.4 Baubles
Forge 13.20.0.2312

Can provide full modlist upon request, or if it is not reproducible.

This is on 1.11.2.

EDIT: I don't think my Pyromancer's Ring is doing anything either, so all of the baubles might be nonfunctional when not in the main inventory.

**Comment by darkhax** [comment]
Hi, thanks for letting me know about this. This is a bug caused by the capitalization of modids changing in 1.11.2 and specifically affects the rings and the null charm. One issue was in Bookshelf, the other was in DarkUtilities. Both have been fixed on the latest alpha release of both, however I would recommend waiting for the stable release of both before updating.

**Comment by Febilian** [comment]
Alright, thanks for the heads up.
